#!/bin/bash

echo "Creating Promise... Response:"
echo

curl -d '{
  "edit": {
    "original": "Matt",
    "modified": "The Dude",
    "accepted": false
  }
}' -H 'content-type:application/json' "http://localhost:3000/users/1/edits"

echo
echo

# echo "Creating Promise... Response:"
# echo

# curl -d '{
#   "promise": {
#     "expiresAt": "Sun Mar 03 2013 13:30:04 GMT-0800 (PST)",
#     "description": "Blackmail walker"
#   }
# }' -H 'content-type:application/json' "http://localhost:3000/api/users/124267827/promises"

# echo
# echo